### ISSUE TITLE
Notifications behave unclearly

### ISSUE THREAD

**Issue by hseg** [ltratt/pizauth#19]
(Arch linux, with dunst 1.9.2)
`pizauth show` will only show one notificiation per account (with no clear timeout information). Even when killed, old notifications suddenly pop up.
Besides all of which, why reimplement notification logic, when there is a perfectly good [crate for it](https://docs.rs/notify-rust/latest/notify_rust/)?

**Comment by ltratt** [comment]
Early versions of pizauth used notify_rust, but it wasn't satisfactory for several reasons (makes no sense when you're not running pizauth in a desktop environment; binary size; and portability amongst them) and was removed in c2ecf94b4d1c17ed024cc8f15777a1632a19020b.

Currently pizauth doesn't have any notion of notifications other than "run a command every so often". It might be a good idea to add a `PIZAUTH_NOTIFICATION_TIME` to indicate how long we've been (intermittently) running that command. If someone wants to do something much more sophisticated, they should be able to write a little program for their favourite notification framework (there are many!).

**Comment by hseg** [comment]
Hrm. Looking through the logic, it appears the issue is (besides an unfortunate
clash between pizauth and my notification framework (which I'm still tracking
down)) an expectation mismatch -- I was expecting `pizauth show` to force either
a new notification, or a fresh authentication cycle if the previous one hadn't
succeeded yet (this could be gated behind a `--force-reauth` flag).
Judging by the logic in `server/mod.rs`, all that's necessary here is to merge
the `TokenState::Pending` logic with the `TokenState::Empty` logic when
responding to `showtoken` (a la the logic when responding to `refresh`) (this is
the second option I'm suggesting here), or to have the response be
```rust
TokenState::Pending { ref url, ref last_notification, .. } => {
    last_notification = None;
    pstate.notifier.notify_changes();
    let response = if *with_url == "withurl" {
        format!("pending:{url:}")
    } else {
        "pending:".to_owned()
    };
    drop(ct_lk);
    stream.write_all(response.as_bytes())?;
}
```

**Comment by hseg** [comment]
(BTW, to avoid this spamming the user's notifications, an alternative value for `auth_notify_cmd` could be
```bash
auth_notify_cmd = "notify-send -p -r $((touch \"$XDG_RUNTIME_DIR/pizauth-$PIZAUTH_ACCOUNT.notif\"; cat \"$XDG_RUNTIME_DIR/pizauth-$PIZAUTH_ACCOUNT.notif\"; echo 0) | head -n1) -t 30000 \"pizauth authentication\" \"<a href=\\\"${PIZAUTH_URL//&/\\&amp;}\\\">$PIZAUTH_ACCOUNT at $(date)</a>\" > \"$XDG_RUNTIME_DIR/pizauth-$PIZAUTH_ACCOUNT.notif\n";
```
cf the [specification regarding replacing
notifications](https://specifications.freedesktop.org/notification-spec/notification-spec-latest.html))
(Though in any case, this is getting complicated enough to be worth writing a
script for)

**Comment by ltratt** [comment]
> I was expecting pizauth show to force either a new notification, or a fresh authentication cycle if the previous one hadn't succeeded yet

`pizauth refresh` should do what you want here.

**Comment by hseg** [comment]
:facepalm: had incorrectly read docs, thought `pizauth show` was the primary mechanism to prompt an authentication.
The partial overlap is confusing, though - perhaps it might be a good idea to exit with error on `pizauth show` if there is no active token, with a message suggesting to call `pizauth refresh`? In any case, this does resolve my issue, thanks!

**Comment by ltratt** [comment]
I think you can get the behaviour want with `pizauth show <act> || pizauth refresh <act>`?

**Comment by hseg** [comment]
Yeah, that works.
