### ISSUE TITLE
Systemd unit?

### ISSUE THREAD

**Issue by hseg** [ltratt/pizauth#21]
It would help packaging if there were an upstream systemd unit.
(Am currently working on this)
Unresolved issues:
- Support dump/restore and reload
- #20 to give a better insight on server status

**Comment by hseg** [comment]
Any reason for preferring invoking the service without `-d` and tearing down with `shutdown` vs invoking with `-d` and having init system just send `SIGTERM`?

**Comment by hseg** [comment]
Also, from systemd docs
> ExecReload=
> ...
> It is thus strongly recommended to either use Type=notify-reload in place of
> ExecReload=, or to set ExecReload= to a command that not only triggers a
> configuration reload of the daemon, but also synchronously waits for it to
> complete.
Is `pizauth reload` synchronous? If not, how big an ask is it to make it so?

**Comment by ltratt** [comment]
> Any reason for preferring invoking the service without -d and tearing down with shutdown vs invoking with -d and having init system just send SIGTERM?

pizauth follows Unix tradition here (I assume that systemd doesn't, but I'm not a Linux person).

> Is pizauth reload synchronous? If not, how big an ask is it to make it so?

It is synchronous (you can see this easily: make a config error, then `pizauth reload` and it'll be reported to you).

**Comment by hseg** [comment]
> > Any reason for preferring invoking the service without -d and tearing down with shutdown vs invoking with -d and having init system just send SIGTERM?
> 
> pizauth follows Unix tradition here (I assume that systemd doesn't, but I'm not a Linux person).
Right, and systemd does indeed support that (if only for backwards compatibility).
It recommends against doing so, however[1](https://www.freedesktop.org/software/systemd/man/systemd.service.html)[2](https://www.freedesktop.org/software/systemd/man/daemon.html) because often this makes it harder to keep track of the service and its resource usage (eg, if PID files aren't well managed).

**Comment by ltratt** [comment]
Unless I'm missing something `-d` does what systemd wants, so there's a way of supporting systemd and respecting the (much wider spread) Unix tradition for daemons.

**Comment by hseg** [comment]
Right, was just checking this was just a tradition thing, and wouldn't break anything. Am a little unconfident of my knowledge here.

**Comment by ltratt** [comment]
Closing this issue, though a PR is always welcome!
