### ISSUE TITLE
[Feature request]: Add verbs forcing notification/cancelling authentication

### ISSUE THREAD

**Issue by hseg** [ltratt/pizauth#29]
At the moment, once an authentication request is made for an account, it cannot be cancelled, leading to notifications every time there is an authentication timeout.
Similarly, the timing of these timeouts is fully under pizauth's control, with no way to manually prompt for a notification (eg if it was lost/buried).

The latter could be added to the standard usage of `pizauth show` to initiate an authentication - just make reinvocations for pending tokens rerun `auth_notify_cmd`. The former would be novel, though. A slightly more useful generalization could be a `pizauth deauth [<account>]` command, which would reset the authentication token for `<account>`.

At the moment, I'm working around the lack of a `force-show` command using my notification daemon's history feature, but it'd be nice to have internal support.
[Workaround attached
](https://github.com/ltratt/pizauth/files/13806002/pizauth-forceshow.txt)

**Comment by ltratt** [comment]
I have continuously thought about `pizauth revoke` but, inexplicably, OAuth2 has no standard support for it. But even if `revoke` only revokes the local token, that's probably still a feature that's worth adding, and it would cover your use case (+more).
