### ISSUE TITLE
pizauth-1.0.4 tag is out of tree

### ISSUE THREAD

**Issue by hseg** [ltratt/pizauth#35]
It appears you retagged the `pizauth-1.0.4` version, but didn't push the updated master, so now the recent history looks like (`git log --graph --decorate --all --oneline`):
```
* caf045c (tag: pizauth-1.0.4) Use the right year.
*   d98d84b (HEAD -> master, origin/master, origin/HEAD) Merge pull request #33 from ltratt/pizauth_1_0_4
|\  
| * ba6d6fc Prepare a 1.0.4 release.
|/  
*   f32cb2f Merge pull request #32 from ltratt/move_bash_completion_install
...
```
It seems to be enough to just `git switch master; git merge pizauth-1.0.4; git push`, though I don't know why https://github.com/ltratt/pizauth/commit/d98d84b28e7391a52c87c83f8952833b71d79e92 still shows up tagged with `pizauth-1.0.4`.

(Only detected this since I mistakenly pre-emptively released the AUR package for 1.0.4 based off of d98d84b, and some tooling now thinks my package is out-of-date)

**Comment by ltratt** [comment]
In this case, the *tag* `pizauth-1.0.4` is the one to use. Tthere was a branch `pizauth_1_0_4` but that was a temporary thing that's now deleted, and perhaps what made you think d98d84b28e7391a52c87c83f8952833b71d79e92 was the right thing?

**Comment by hseg** [comment]
Yeah, probably. Regardless, the situation is still that no branch points to caf045c, that on Github d98d84b is displayed as being tagged `pizauth-1.0.4`.
Moreover, I'm not certain why caf045c is not being merged into master -- isn't it intended to be part of the mainline development history?

**Comment by ltratt** [comment]
> Moreover, I'm not certain why https://github.com/ltratt/pizauth/commit/caf045cb05a9629c95990ded7be85170e457ade6 is not being merged into master

Huh, you're right --- that is *very* weird. GitHub had the commit, which had only ever existed on the master branch, but somehow hadn't updated its master branch? I can only assume this was the result of some sort of GitHub glitch, as I can't explain any other way of it happening (but maybe that's narrowness of thinking on my part). Fortunately, by forcibly pushing that commit to master, it now shows up on the master branch. I shall add "check it actually appears in the UI" to my list of "things that seem like they shouldn't go wrong but can" mystery pile!

**Comment by hseg** [comment]
On Wed, Apr 10, 2024 at 11:37:41AM -0700, Laurence Tratt wrote:
> > Moreover, I'm not certain why https://github.com/ltratt/pizauth/commit/caf045cb05a9629c95990ded7be85170e457ade6 is not being merged into master
> 
> Fortunately, by forcibly pushing that commit to master, it now shows up on the master branch.

Checking, `master` indeed now contains the tag.
However, for some reason, Github UI still displays both https://github.com/ltratt/pizauth/commit/caf045cb05a9629c95990ded7be85170e457ade6 and https://github.com/ltratt/pizauth/commit/d98d84b28e7391a52c87c83f8952833b71d79e92 as being tagged `pizauth-1.0.4`, despite that making absolutely no sense in re git semantics.
Maybe report to https://github.com/orgs/community/discussions/categories/repositories ?

**Comment by hseg** [comment]
On Thu, Apr 11, 2024 at 07:59:07AM -0700, Laurence Tratt wrote:
> In https://github.com/ltratt/pizauth/tags I only see `pizauth-1.0.4` pointing to https://github.com/ltratt/pizauth/commit/caf045cb05a9629c95990ded7be85170e457ade6?

Right, but if you look at the page for d98d84b, ie https://github.com/ltratt/pizauth/commit/d98d84b28e7391a52c87c83f8952833b71d79e92, under the commit message it is labeled as `pizauth-1.0.4` as well.
I'm chalking this up to a Github UI problem.
Am asking on #git, perhaps they have an idea what's going on here.

**Comment by hseg** [comment]
Egg on my face -- I hadn't noticed this is by design in the Github UI, cf https://github.com/ltratt/pizauth/commit/602d5f3ce5bf7fb40f0fa8be7e8dcd48093ef9c2 -- the design is not to show `git log -1 --oneline --decorate <commit>`, but rather `git branch --contains <commit>` and `git tag --contains <commit>`.
i.e. Github isn't showing the branches/tags whose *tips* are this commit, but rather branches/tags which *contain* this commit (which is useful eg for figuring out which versions contain a particular commit)
