### ISSUE TITLE
Getting an error with mbsync

### ISSUE THREAD

**Issue by ldangelo** [ltratt/pizauth#36]
Authenticating with SASL mechanism XOAUTH2...
Error performing SASL authentication step: SASL(-1): generic failure: Unable to find a callback: 18948

Any suggestions on how too troubleshoot this?  Is there a way to see what port pizauth is listening on?  Might be good information to add too 'info' or 'status'.

Thank you in advance for any advice.

**Comment by ltratt** [comment]
A quick search suggests this might be some combination of mbsync + OS X? https://github.com/moriyoshi/cyrus-sasl-xoauth2/issues/9

If not, I'll need more details: platform, config (minus personal details of course!), and so on.

**Comment by ldangelo** [comment]
DOH!  Sorry, should have done more research before submitting an issue.  I am in fact on osx...  Let me dig into this and see what I find...  I will report back here either way.  BTW) Thank you for building this software..  Love the approach...

**Comment by ldangelo** [comment]
This was in fact due to mbsync on Mac OS.  It appears there is an issue with the built-in Cyrus-sasl implementation.  To resolve I used nix to install sasl & coauth-sasl and then created on overlay to build using the newly installed sasl implementations...

Here is a link too my nix repo if anyone is interested: https://github.com/ldangelo/nix

**Comment by ltratt** [comment]
Thanks for the update and best of luck!
