### ISSUE TITLE
Instructions on running pizauth as a launch agent on osx

### ISSUE THREAD

**Issue by ldangelo** [ltratt/pizauth#38]
Took me a while to figure this out so I thought I would share here.  I was trying to get pizauth to run as a user agent under osx.  When I would run from the shell it worked fine, but when launched as an agent it did not.  After looking at the output of 'pizauth info' I realized it was using different cache directories depending on how it was launched.

While running as a launch agent I needed to set two environment variables for it to work properly:

HOME=/Users/myuser
XDG_DATA_HOME=$HOME/.local/share

Hope this saves someone a little time in the future.

Here is my pizauth.daemon.plist:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>EnvironmentVariables</key>
	<dict>
		<key>HOME</key>
		<string>/Users/ldangelo</string>
		<key>XDG_DATA_HOME</key>
		<string>/Users/ldangelo/.local/share</string>
	</dict>
	<key>KeepAlive</key>
	<true/>
	<key>Label</key>
	<string>pizauth.daemon</string>
	<key>ProcessType</key>
	<string>Standard</string>
	<key>ProgramArguments</key>
	<array>
		<string>/usr/local/bin/pizauth</string>
		<string>server</string>
		<string>-c</string>
		<string>/Users/ldangelo/.config/pizauth.conf</string>
		<string>-d</string>
		<string>-vvvvv</string>
	</array>
	<key>StandardErrorPath</key>
	<string>/tmp/pizauth.out</string>
</dict>
</plist>

**Comment by ltratt** [comment]
Is `$HOME` not set by default on OS X? That would surprise me a bit! I can well imagine that `$XDG_DATA_HOME` isn't set, though. In theory -- assuming I got the code right! -- you should only need to set one of `$HOME` or `$XDG_DATA_HOME`. Do you have to set both or is one of them sufficient?

**Comment by ldangelo** [comment]
Full disclosure, I'm using nix-darwin to configure the agent.  If I don't set $HOME I get an error saying it's not set.

**Comment by ltratt** [comment]
I must confess to ignorance of nix-darwin and its possible effects! I know earlier versions of pizauth worked "raw" on OS X, but things could have changed since then. If you use pizauth without nix-darwin, does it work as expected without fiddling with environment variables?

[I must admit that I don't know what a Unix process/system should do if `$HOME` isn't set. I'd always assumed it was set all the time...]

**Comment by ldangelo** [comment]
from the command line it works perfectly...  It's when I try and launch it as an agent that it appears HOME is not set...  Also, even with HOME set if I don't set XDG_DATA_HOME it uses a different cache directory than the command line.  So pizauth status says it's not running...

-LeoD

**Comment by ltratt** [comment]
Aha, I think there are two separate things going on:

1. On your machine / OS, there are situations where a daemon can be run without `$HOME` being set (and you're under an OS where `$XDG_DATA_HOME` isn't a thing).
2. `$XDG_DATA_HOME` has different semantics than `$HOME`: it's not the user's home directory but a directory where people can plonk data into directly. [e.g. on my machine I might set `$XDG_DATA_HOME` to `/home/ltratt/.cache`.]

In retrospect, I think it would be better if pizauth told you to define `$HOME` and didn't mention `$XDG_DATA_HOME` as the latter is poorly understood (see below for why I got it wrong too!). *Maybe* pizauth can work out your `$HOME` directory even if the environment variable isn't set (e.g. reading `/etc/passwd`)? It would need someone to work out if that would help someone in your situation -- I'd happily accept a PR which improves the situation.

Having now read the [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) more carefully, pizauth should actually be using `$XDG_RUNTIME_DIR`. That's something I wasn't expecting, but is a useful outcome anyway!

**Comment by ltratt** [comment]
https://github.com/ltratt/pizauth/commit/c9ea6170c8c89375cef4855f10dbd31ffd12b408 changes where pizauth places its control socket. This should also, I hope, solve the problem of `$HOME` not being set (assuming that you have specified `-c` to tell pizauth where your config file is set). Please give this a shot, though note that you'll have to shutdown your existing pizauth server and run one based on this new commit.

**Comment by ltratt** [comment]
@ldangelo Does the new commit help things, in the sense that you no longer need to set `$HOME` or any `$XDG` variables?
