### ISSUE TITLE
Hotmail: You can't sign in here with a personal account. Use your work or school account instead.

### ISSUE THREAD

**Issue by trembel** [ltratt/pizauth#40]
Hi,

I'm trying to use pizauth to authenticate my personal Hotmail account using OAuth and isync, but getting the error "You can't sign in here with a personal account. Use your work or school account instead." after following the link generated by pizauth. My config is:

```
account "hotmail" {
    auth_uri = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize";
    auth_uri_fields = { "login_hint": "....@hotmail.com" };
    token_uri = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
    client_id = "7068f0e2-17d9-4413-8bed-0959dd92e5a8";
    scopes = [
      "offline_access",
      "https://outlook.office365.com/IMAP.AccessAsUser.All",
      "https://outlook.office365.com/SMTP.Send"
    ];
}
```

I tried with different client_id's I could find in the internet (all of them I think are from thunderbird somehow), but all gave the same result..

Has someone been able to authenticate a personal hotmail/outlook account?

**Comment by ltratt** [comment]
You will *probably* also need a corresponding `client_secret` (not every site requires it, but most do).

**Comment by trembel** [comment]
I tried also some with client secrets, e.g.
```
    client_id = "08162f7c-0fd2-4200-a84a-f25a4db0b584";
    client_secret = "TxRBilcHdC6WGBee]fs?QR:SJ8nI[g82";
```
(https://simondobson.org/2024/02/03/getting-email/), which resulted in the same error.

**Comment by trembel** [comment]
Might be that the client_id is not valid anymore (thunderbird changed recently):
https://hg.mozilla.org/comm-central/rev/8a2ef67503dff486b842a6fd35bc99bf1d223137#l6.122

However, using those informations (no client secret) results in
```
We're unable to complete your request

invalid_request: The provided value for the input parameter 'redirect_uri' is not valid. The expected value is a URI which matches a redirect URI registered for this client application.
```
as the redirect_uri is `http://localhost`. However, changing to TLS fails, as the server is not available with TLS:
```
An error occurred during a connection to localhost:37447. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG
```

**Comment by trembel** [comment]
Just tried it using a reverse proxy (with self-signed certificate) to the server, which worked and got me the token.

**Comment by ltratt** [comment]
Glad to hear!

**Comment by trembel** [comment]
Thanks for your help and time. I wouldn't say its solved; It's a manual and 'terrible' workaround - which helped me to get an understanding of what is going wrong. However it is IMO not really applicable, thus I would like to request the possibility of implementing / adding a self-signed https server for localhost.

**Comment by ltratt** [comment]
Just to check: you're saying that hotmail requires the redirect URI to be an `https` URL, not `http`? I did wonder if we'd come across that at some point. In your situation, did a self-signed `https` proxy work? If so, yes, adding an HTTPS server to pizauth would be a good idea, ideally one that autogenerates certificates and so on, to require minimal setup by the user. I doubt I will get around to that any time soon, but PRs are welcome!

**Comment by trembel** [comment]
I'm not to familiar with OAuth. I think, its Microsoft requesting the same redirect URI in the request, as in the registered Azure App. As most companies do not allow for allowing a custom Azure App to access their mail, a lot of people rely on the Thunderbird "credentials" - which have the redirect_uri pointing to `https://localhost` (see marked line here: https://hg.mozilla.org/comm-central/rev/8a2ef67503dff486b842a6fd35bc99bf1d223137#l6.131).

I tried with a self-signed certificate, which worked fine (and is the only option when using localhost as redirect URI). If I find time, I will try to implement it using rustls (which afaik has capabilities to directly generate certificates) and hyper.

**Comment by ltratt** [comment]
I don't know much about rusttls, but it does sound a plausible building block.

I have a bias against hyper, since that pulls in tokio, and bloats things considerably. pizauth accidentally included tokio in the past (removed in c2ecf94b4d1c17ed024cc8f15777a1632a19020b, reducing the binary by 25%!), and I also removed it from snare (https://github.com/softdevteam/snare/commit/1263ececbeb693bce5ef89111b65baf8a74fde21), leading to a similar reduction in binary size. In the latter case, there also seemed to be a tiny, but persistent, memory leak from tokio that I never got to the bottom of, but which is now gone.

My hope would be that we can use rusttls (or similar) but maintain a completely minimal HTTP/HTTPS server underneath, just as with [pizauth's current HTTP server](https://github.com/ltratt/pizauth/blob/master/src/server/http_server.rs) which does the job at 367Loc!

**Comment by rrrnld** [comment]
@trembel thanks for implementing tls support! i had the exact same issue as i was trying to configure msmtp / isync to use oauth2 for my hotmail account.

After obtaining the token, I get redirected to the following URI: https://localhost:46317/?error=invalid_scope&error_description=The%20provided%20resource%20value%20for%20the%20input%20parameter%20%27scope%27%20is%20not%20valid.&state=dBRaVLRl-jY

Do you have any idea why I get the `invalid_scope` error? Sorry if this is beyond pizauth now, maybe it's still helpful as I imagine it's a common enough usecase. My config file looks like this:

```
account "hotmail" {
    auth_uri = "https://login.microsoftonline.com/common/oauth2/v2.0/authorize";
    auth_uri_fields = { "login_hint": "...@live.com" };
    token_uri = "https://login.microsoftonline.com/common/oauth2/v2.0/token";
    client_id = "9e5f94bc-e8a4-4e73-b8be-63364c29d753";
    scopes = [
      "offline_access",
      "https://outlook.office365.com/IMAP.AccessAsUser.All",
      "https://outlook.office365.com/SMTP.Send"
    ];
    redirect_uri = "https://localhost";
}
```

It's basically the same as posted above, but it uses the current thunderbird client ID, and the `redirect_uri` to `https://localhost` (like thunderbird does). Note that my e-mail address uses the `live.com` domain, but that should not have any effect on the requested scopes I hope?

Any help would be very appreciated.

As for the binary I'm using, I built a version of pizauth from revision ca2379c10748de63a14472d9fb8a7e5cbbd7dfac using nix:

```nix
{
  lib,
  rustPlatform,
  fetchFromGitHub,
  installShellFiles,
  stdenv,
  darwin,
}:

rustPlatform.buildRustPackage rec {
  pname = "pizauth";

  # see https://github.com/ltratt/pizauth/pull/41
  version = "ca2379c10748de63a14472d9fb8a7e5cbbd7dfac";

  src = fetchFromGitHub {
    owner = "ltratt";
    repo = "pizauth";
    rev = version;
    hash = "sha256-sJnWeWYBnB+vS/Gjm9qPyhISzISNwBzY5h3aUnFsyHo=";
  };

  cargoHash = "sha256-yxm5/TUOhD1rY6hIJ5TMJxWSY3Px2gtZJ9GcE4PKlh0=";

  nativeBuildInputs = [ installShellFiles ];

  buildInputs = lib.optionals stdenv.isDarwin [ darwin.apple_sdk.frameworks.Security ];

  postInstall = ''
    installShellCompletion --cmd pizauth \
      --bash share/bash/completion.bash
  '';

  meta = {
    description = "Command-line OAuth2 authentication daemon";
    homepage = "https://github.com/ltratt/pizauth";
    changelog = "https://github.com/ltratt/pizauth/blob/${src.rev}/CHANGES.md";
    license = with lib.licenses; [
      asl20
      mit
    ];
    maintainers = with lib.maintainers; [ moraxyc ];
    mainProgram = "pizauth";
  };
}
```

**Comment by ltratt** [comment]
Aha, thanks for pointing out the fix!

**Comment by trembel** [comment]
> @trembel thanks for implementing tls support!

You're welcome :)

I noticed your issue with the invalid scope as well, but figured it out before even starting the TLS implementation/testing. Sadly, I forgot to mention it - so my apologize @rrrnld that you had to debug yourself...

**Comment by ltratt** [comment]
Thanks both. I've updated the [recipes](https://tratt.net/laurie/src/pizauth/recipes.html) page with this suggestion: alas, it seems that both the `office.com` and `office365.com` recipes are needed for different people.
