### ISSUE TITLE
warnings and new tag

### ISSUE THREAD

**Issue by dkwo** [ltratt/pizauth#46]
Thanks for making this software. I'm trying to package it for Void Linux https://github.com/void-linux/void-packages/pull/53263
Do you mind tagging v1.0.6 also on github, besides your homepage?

When building on linux, I noticed this two warnings:
```
=> pizauth-1.0.6_1: running do_install ...
  Installing pizauth v1.0.6 (/builddir/pizauth-1.0.6)
warning: package `url v2.5.3` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
warning: elided lifetime has a name
   --> src/server/state.rs:283:51
    |
282 | impl<'a> CTGuard<'a> {
    |      -- lifetime `'a` declared here
283 |     fn new(guard: MutexGuard<'a, LockedState>) -> CTGuard {
    |                                                   ^^^^^^^ this elided lifetime gets resolved as `'a`
    |
    = note: `#[warn(elided_named_lifetimes)]` on by default

warning: `pizauth` (bin "pizauth") generated 1 warning
```
Do you think they're relevant?

**Comment by ltratt** [comment]
Oops, the 1.0.6 tag is now pushed.

The lifetime warning is not important, and probably is a lint in 1.83.0 that I haven't yet seen (I'm on 1.82.0).

The `url` yanking is something you might want to fix when packaging if you think it was yanked for a reason that affects you. I don't know what was changed to cause the yanking (alas there's no `CHANGES.md`), so I'm not sure if a release of pizauth just for that is worthwhile. [This is a downside of each program hard-coding its own dependencies, alas!]

**Comment by dkwo** [comment]
Thanks a lot. I think it should be fine to address these once you make a new release. Also it might be worth to add zsh completions. It's now working fine for me with microsoft and google accounts. I plan to write a dinit user service later.

**Comment by dkwo** [comment]
Forgot to mention: it would also be great to have a separate command to install the binary and the rest (man, services, conf), e.g. `make install data`, so that distros can still build and install the binary their own way but do not have to hand-pick the rest. See https://github.com/AsahiLinux/speakersafetyd/commit/f069160e33359fb14d8f03679c92cddc6dbe1d4b for an example. Of course these are all minor things, so no pressure at all.

**Comment by ltratt** [comment]
I'm happy to take PRs on these.

**Comment by dkwo** [comment]
@ltratt One more question: if using "pizauth dump | age..." in the service (before shutdown), does it still make sense to keep `token_event_cmd = "pizauth dump | age..."` in pizauth.conf?

**Comment by ltratt** [comment]
`token_event_cmd` is run whilst pizauth is alive as tokens are updated: you don't want to run it just at shutdown IMHO.
